add keycloak toggle and configs
greymatter-io/greymatter-core pull request #106
Opened 2022-10-28 18:13 UTC by tilleryd

2022-11-14 18:08 UTC, neagle approved these changes

2022-11-15 23:37 UTC, jack-bischoff commented on inputs.cue
> +		keycloak:          string | *"quay.io/keycloak/keycloak:19.0.3"
Are we allowed to pull from quay?

2022-11-16 00:39 UTC, tilleryd commented on inputs.cue
> +		keycloak:          string | *"quay.io/keycloak/keycloak:19.0.3"
Yes, that’s public Quay repo, not ours.

2022-11-16 01:13 UTC, jack-bischoff requested changes

2022-11-16 01:13 UTC, jack-bischoff commented on inputs.cue
> +		keycloak:          string | *"quay.io/keycloak/keycloak:19.0.3"
Very true

2022-11-18 16:24 UTC, jack-bischoff approved these changes

2022-11-18 20:57 UTC, jack-bischoff approved these changes

2022-11-18 20:59 UTC, merged